<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="phaet.local" failures="1" tests="3" name="iOS" time="39.384" errors="0" timestamp="2023-07-27T18:41:05 KRAT">
  <testcase classname="tests.LoginTests" name="invalidPassword" time="8.934">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.bla] but found [Username and password do not match any user in this service.]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.bla] but found [Username and password do not match any user in this service.]
at tests.LoginTests.invalidPassword(LoginTests.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase classname="tests.LoginTests" name="invalidUsername" time="7.711"/>
  <testcase classname="tests.LoginTests" name="successfulLogin" time="11.887"/>
</testsuite> <!-- iOS -->
